### ISSUE TITLE
JsonNode as an  interface

### ISSUE THREAD

**Issue by leocrawford** [hibnico/jackson-jsonpath#1]
Is there any chance of using a Interface instead of JsonNode, JsonArray, etc? This would help me as I use persistent nodes.

The code would need to change little, simply provide matching interfaces - and for classes where you want to take a concrete JsonNode (as input) have a delegating class. 

Ideally Jackson would use interfaces rather than methods, but as it doesn't this would be really helpful. I'm happy to propose some changes if that helps.

**Comment by hibnico** [comment]
Actually this project is a sort of fork from https://github.com/jayway/JsonPath. I "forked" it because I wanted to get rid of the useless (to my use case) abstraction over the representation of JSON, which implies useless computation and bean creation, which seems a waste to me. And this fork is becoming a complete rewrite since the implementation of the parser of path is quite limited and doesn't follow parser implementation standards, that why jayway implementation isn't referenced here.

But for your use case, you might be better interested in https://github.com/jayway/JsonPath

**Comment by leocrawford** [comment]
Thanks.. I had seen the package, but assumed this was just a later version.  

I appreciate your quick reply, and will keep an eye on your developments.
